# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/karchive': '@latest'
    'frameworks/kauth': '@latest'
    'frameworks/kcodecs': '@latest'
    'frameworks/kcompletion': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kdbusaddons': '@latest'
    'frameworks/kdeclarative': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kiconthemes': '@latest'
    'frameworks/kio': '@latest'
    'frameworks/kjobwidgets': '@latest'
    'frameworks/kpackage': '@latest'
    'frameworks/kparts': '@latest'
    'frameworks/kservice': '@latest'
    'frameworks/ktexteditor': '@latest'
    'frameworks/ktextwidgets': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/kxmlgui': '@latest'
    'frameworks/solid': '@latest'
    'frameworks/sonnet': '@latest'
    'frameworks/syntax-highlighting': '@latest'
    'plasma/plasma-framework': 'kf5'
Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']
